Repository palantir/witchcraft-go-error, pull requests merged in 2020-10, with the labels that each got.

#49 Make Werror interface
  changelog/@unreleased/pr-49.v2.yml
  stacktrace.go
  werror.go
  werror_printer.go
  werror_test.go
Labels: autorelease

#54 Fix: Fix frame skips in NewStackTrace and NewStackTraceWithSkips
  changelog/@unreleased/pr-54.v2.yml
  stacktrace.go
  werror.go
  werror_test.go
Labels: autorelease, merge when ready

#55 Fix: Fix stack traces for Error and Wrap constructors
  changelog/@unreleased/pr-55.v2.yml
  werror.go
  werror_test.go
Labels: autorelease

#56 Clean up error constructor test
  werror_test.go
Labels: no changelog

#53 fix: Handle nil ParamStorer
  changelog/@unreleased/pr-53.v2.yml
  params.go
  werror_test.go
Labels: merge when ready
